version: "3"

services:
 mosquitto:
  image: eclipse-mosquitto:latest
  container_name: mqttmos
  restart: always
  volumes:
   - ./conf:/mosquitto/config
   - ./data:/mosquitto/data
   - ./log:/mosquitto/log
  ports:
   - "1883:1883"
   - "9001:9001"
